### ISSUE TITLE
Lora saved to incorrect folder after making on mac

### ISSUE THREAD

**Issue by DearDhruv** [hako-mikan/sd-webui-supermerger#11]
I have mac M2- 13.2.1 (22D68), 
After creating the LoRA from checkpoints - it creates unnecessary directories with the same path it has to the Lora model path and saves as below: 

<img width="2297" alt="image" src="https://user-images.githubusercontent.com/1201239/220864427-272d7bd8-c99d-4733-b321-3d99e7a5dc84.png">

I do not know python code, hence no PR for now from my side :)

**Comment by hako-mikan** [comment]
Thanks reporting. I fixed, but  I cannot test it. So please try it.

**Comment by DearDhruv** [comment]
@hako-mikan 
Updated to the latest version, but the issue still persists... 
Let me know how can I help!!!

**Comment by DearDhruv** [comment]
More findings: @hako-mikan 

So the Path actually consists of the below files:
OUTPUT FILE: `path/to/LORA/my_lora.safetensors` in webs UI.
Checkpoint A: `path/to/SD/xyzA.ckpt`
Checkpoint B: `path/to/SD/pqrB.ckpt`

It gets combined and creates directories as it has in the names. for ex: `path/to/LORA/` `lora_` `/path/to/SD/xyzA` `/path/to/SD/xyzB` `my_lora.safetensors` Spaces added to separate the changes of path :) 

I think the code should just take the file name instead of path to file and file name. 

Hope this can help...

**Comment by hako-mikan** [comment]
Did you restart the web-ui executable after the update? This extension is not reflected update just by updating. If you still have problems after restarting, please let me know what happens if you specify a file name in "filename(option).

**Comment by DearDhruv** [comment]
I see it save correctly, I have applied the Restart UI after the update. But now I have started fresh it works. 

Thanks, after your last commit, it works nicely and saves correctly. 
Closing the issue :)
