### ISSUE TITLE
I met an error. smergegen() takes 23 positional arguments but 25 were given

### ISSUE THREAD

**Issue by KevingKang** [hako-mikan/sd-webui-supermerger#20]
Traceback (most recent call last):
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Program Files (x86)\SD WebUI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: smergegen() takes 23 positional arguments but 25 were given
![image](https://user-images.githubusercontent.com/39239376/222335520-5c72d03a-81af-4566-bd64-fea1f04bca49.png)

**Comment by sbuldan** [comment]
same here

**Comment by hako-mikan** [comment]
Thanks reporting!
This problem was fixed.

**Comment by SnownICE** [comment]
> Thanks reporting! This problem was fixed.

emmm.... i chose the "Sequential XY Merge and Generation" and it still throw the similar error
`Traceback (most recent call last):
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: numanager() takes 26 positional arguments but 28 were given`
![chrome_Ca4vLhE9AV](https://user-images.githubusercontent.com/80137973/222407186-1e399be2-5638-419f-b15e-d5cd6a054457.png)

**Comment by hako-mikan** [comment]
After updating, The effect will not be reflected unless web-ui is restarted. Looking at that screen, it does not appear to have been updated correctly.

**Comment by Daemonrat** [comment]
I also ran into this error, but I'm running on Ubuntu, so I'm not sure if it's just incompatible with my system.

**Comment by SnownICE** [comment]
> I also ran into this error, but I'm running on Ubuntu, so I'm not sure if it's just incompatible with my system. Edit: Sorry for my ignorance, I deleted the extension, reinstalled it, and now it works 💯

emmm.... i run on Linux and windows,but both throw errors.It could be the model problem,but I haven't looked into it
